# Generated by Django 3.2.5 on 2021-11-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=30)),
                ('maqola', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.URLField()),
                ('maqolaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.maqola')),
            ],
        ),
    ]
